global:
  image: 
    defaultImageRegistry: r.gamewarden.io
    defaultImageRepository: base

microservices:
  santonio:
    pullPolicy: Always
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: true
      runAsNonRoot: false
    volumeMounts:
      - name: nginx-cache
        mountPath: /var/cache/nginx
    volumes:
      - name: nginx-cache
        emptyDir:
          medium: Memory 
    image:
      tag: "1.0"

manifests:
  vs:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: hackathon
    spec:
      gateways:
      - istio-system/public
      hosts:
      - satonio.gw.local
      http:
      - route:
        - destination:
            host: santonio
            port:
              number: 8080
