global:
  image: 
    defaultImageRegistry: r.gamewarden.io
    defaultImageRepository: base

microservices:
  santonio:
    pullPolicy: Always
    # selectorLabels:
    #   protect: keycloak
    service:
      port: 8080
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 101
      runAsGroup: 101

manifests:
  vs:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: santonio
    spec:
      gateways:
      - istio-system/public
      hosts:
      - santonio.gw.local
      http:
      - route:
        - destination:
            host: santonio
            port:
              number: 8080
  twobrief:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      labels:
        app: santoniopub
      name: santoniopub
    spec:
      gateways:
        - istio-system/public-afwerx
      hosts:
        - "santonio.gamewarden.io"
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: santonio
                port:
                  number: 8080

