global:
  image: 
    defaultImageRegistry: r.gamewarden.io
    defaultImageRepository: base

microservices:
  santonio:
    pullPolicy: Always
    selectorLabels:
      protect: keycloak
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 65532
      runAsGroup: 65532
    image:
      tag: "0.0"

manifests:
  vs:
    apiVersion: networking.istio.io/v1
    kind: VirtualService
    metadata:
      name: hackathon
    spec:
      gateways:
      - istio-system/public
      hosts:
      - satonio.gw.local
      http:
      - route:
        - destination:
            host: santonio
            port:
              number: 8080
